### ISSUE TITLE
Missing declaration of THINBASIC_MSXML2_* constants

### ISSUE THREAD

**Issue by petrSchreiber** [ThinBASIC/thinBasic_MSXML2#1]
The thinBasic_MSXML2.rc file uses constants matching the pattern THINBASIC_MSXML2_FILEDESCRIPTION, but these are not declared in any file in the repo.

In order to fix it, .h file should be added.

**Comment by ErosOlmi** [comment]
I should have fixed and hopefully this can be the way for all other modules.
Inside /module_core/ repository I've added all needed files for a module to compile.
Resource.h has been taken for official PB10.x version and copied in /module_core/. In this way we are independent from other resources.
If this solve the problem for you too, please close this issue

**Comment by petrSchreiber** [comment]
Perfect, thank you 👍

**Comment by ErosOlmi** [comment]
I think this could be the way to go for all other modules.
So, go on with this module also to try to find a common way for all modules.
